add iterAll
dmitryDevGoMid/gofermart pull request #1
Opened 2023-12-28 09:56 UTC by dmitryDevGoMid

2023-12-29 14:26 UTC, edylcrm requested changes

2023-12-29 14:26 UTC, edylcrm commented on cmd/luna/main.go
> +package main
Это для теста нужно было?

2023-12-29 14:26 UTC, edylcrm commented on internal/pkg/pipeline2/pipeline.go
> +package pipeline2
А зачем pipeline и pipeline2? Нельзя использовать один?

2023-12-29 14:26 UTC, edylcrm commented on internal/service/process/accrual/run.go
> +	p.AddPipe(authentication.CheckJWTToken{}, &pipeline.PipelineOpts{
Вообще выглядит очень странно. Зачем это все запускать в отдельных горутинах, если можно под часть функционала написать middleware, а часть сделать синхронной?

2023-12-29 18:04 UTC, dmitryDevGoMid commented on cmd/luna/main.go
> +package main
Да для тестов, чтобы номер получить для запроса с сервису

2023-12-29 18:10 UTC, dmitryDevGoMid commented on internal/service/process/accrual/run.go
> +	p.AddPipe(authentication.CheckJWTToken{}, &pipeline.PipelineOpts{
Хотел полностью реализовать без миделлваре, например могут быть эндпоинты, в которых аутентификация не требуется, тогда придется добавлять условие и так несколько. 
Ещё как вариант аутентификация через другой механизм на одном из эндпоинтов. Которая отличается от текущей, но это конечно исключение ))

2023-12-30 05:28 UTC, dmitryDevGoMid commented on internal/pkg/pipeline2/pipeline.go
> +package pipeline2
Когда реализовывал показалось, что в первом случае, при обычном не обойтись без каналов, которые требуются для выхода из пайплайна и воркеров.

2024-01-10 09:43 UTC, edylcrm requested changes

2024-01-10 09:43 UTC, edylcrm commented on internal/pkg/pipeline/stage.go
> +		go func() {
[BLOCKER] т.к. каждый pipline запускается в отдельной горутине может быть так что pipline который должен выполняться строго после определенного pipline может выполниться раньше.
Я очень долго смотрю на реализацию pipline. Она очень сложная для простой логики сервиса. Я предлагаю это все таки реализовать без pipline.

2024-01-10 09:43 UTC, edylcrm commented on internal/pkg/pipeline/pipeline.go
> +		input = i.Output()
[BLOCKER] а почему сюда попадает послений?

2024-01-10 09:43 UTC, edylcrm commented on internal/service/process/registration/run.go
> +	sync.Lock()
[BLOCKER] зачем здесь Lock и Unlock? Не вижу здесь конкурентного доступа к каким то структурам

2024-01-10 09:43 UTC, edylcrm commented on internal/service/process/registration/run.go
> +		log.Println(err)
[BLOCKER] почему ошибка не возвращается?

2024-01-10 09:43 UTC, edylcrm commented on internal/service/process/withdraw/run.go
> +	sync.Lock()
[BLOCKER] здесь тоже не понятно зачем Lock/Unlock

2024-01-10 09:43 UTC, edylcrm commented on internal/service/process/withdraw/run.go
> +		<-p.Output()
[BLOCKER] Зачем здесь дожидаться Output? Тем самым порождая отдельную горутину на каждый запрос? Ниже же есть p.Stop()

2024-01-10 09:43 UTC, edylcrm commented on internal/service/process/withdraw/run.go
> +	go func() {
[BLOCKER] Здесь можно обойтись без гоуртины

2024-01-10 09:43 UTC, edylcrm commented on internal/service/process/withdraw/run.go
> +	data.Default.Repository = rep
[BLOCKER] А если нужно будет добавить еще какое-то количество зависимостей? Эта структура тогда превратить в Service Locator. Такое решение не выглядит гибко, чем больше логики, тем больше зависимостей и связанности по всему проекту

2024-01-10 09:43 UTC, edylcrm commented on internal/service/process/withdraw/run.go
> +	data.Default.Cfg = cfg
[BLOCKER] хранить context выполнения запроса где-то внутри структуры - антипаттерн. Контекст нужно передавать так где он нужен первым параметром функции.

2024-01-10 09:43 UTC, edylcrm commented on internal/service/process/withdraw/run.go
> +	p := pipeline.NewConcurrentPipeline()
[BLOCKER] На один пользовательский запрос в текущей реализации порождается около 15 горутин, горутина это не бесплатная штука и на большом кол-ве запросов может приводить к деградации. Всю логику можно написать синхронно, что сделает код читабельней, на него можно проще написать unit тесты и вообще поддерживать. Текущая реализация очень сложная, я такое бы в прод не пустил.
Здесь достаточно будет написать unit тесты на это все

2024-01-10 09:43 UTC, edylcrm commented on internal/pkg/pipeline/pipeline.go
> +package pipeline
[BLOCKER] можно на весь pipeline написать unit тетсы? Кажется что сделать это будет очень сложно

2024-01-10 09:43 UTC, edylcrm commented on internal/service/process/loyalty/run.go
> +	ticker.Stop()
[BLOCKER] а почему именно здесь stop? Лучше это делать там где создается ticker

2024-01-23 15:13 UTC, merged